if: branch = master
language: r

matrix:
  include:
  - r: release
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
  - r: release
    os: osx
    osx_image: xcode7.3
    disable_homebrew: true
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
