if: branch = master
matrix:
  include:
  - r: release
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
  - r: release
    os: osx
    osx_image: xcode7.3
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
